"""empty message

Revision ID: 205945268d35
Revises: ab9cd71071e8
Create Date: 2024-08-11 03:15:32.488667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205945268d35'
down_revision = 'ab9cd71071e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('file', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_updated_at'))
        batch_op.drop_index(batch_op.f('ix_document_title'))
        batch_op.drop_index(batch_op.f('ix_document_created_at'))

    op.drop_table('document')
    # ### end Alembic commands ###
