"""empty message

Revision ID: 4a47a74b65a8
Revises: 420c8bb7200b
Create Date: 2024-08-10 08:03:22.051407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a47a74b65a8'
down_revision = '420c8bb7200b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_camera_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camera_type'))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
