"""empty message

Revision ID: ab9cd71071e8
Revises: 4a47a74b65a8
Create Date: 2024-08-10 10:24:13.805424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9cd71071e8'
down_revision = '4a47a74b65a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('running', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detector_type'), ['type'], unique=False)

    op.create_table('detected_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detector_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('frame', sa.LargeBinary(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['detector_id'], ['detector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detected_object', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detected_object_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_detected_object_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detected_object', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detected_object_timestamp'))
        batch_op.drop_index(batch_op.f('ix_detected_object_name'))

    op.drop_table('detected_object')
    with op.batch_alter_table('detector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detector_type'))

    op.drop_table('detector')
    # ### end Alembic commands ###
